### ISSUE TITLE
Great tool

### ISSUE THREAD

**Issue by James94665** [M0V3/TitanAccountConverter#1]
+rep Now to get a way to auto add csgo to the accounts i make

**Comment by Holfz** [comment]
any endpoint for adding csgo into library ? 

> ![gif](https://camo.githubusercontent.com/d717727921b7bb4c6c990f5ae9c5b59e69afad14/68747470733a2f2f692e6779617a6f2e636f6d2f64613065623436366230363538306137636432626531396433376565633439302e676966)
> :^)
> 
> Maybe I'll release the bot in a few days. Maybe.
