### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Holfz** [M0V3/TitanAccountConverter#2]
![image](https://user-images.githubusercontent.com/32639831/50724950-70c78a00-1128-11e9-9b58-c3d138d5c86c.png)

**Comment by M0V3** [comment]
Make sure theres no blank line in your input, gonna push a fix in a few minutes

**Comment by Holfz** [comment]
> Make sure theres no blank line in your input, gonna push a fix in a few minutes

Oh i found why add line by line working.

Thanks!!

**Comment by M0V3** [comment]
Fixed with release [v1.1](https://github.com/M0V3/TitanAccountConverter/releases/tag/v1.1)
